import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "../lib/api";
import { useSettings } from "../hooks/use-settings";

export function Settings() {
  const client = useQueryClient();
  const query = useSettings();
  const [enabled, setEnabled] = useState<boolean | null>(null);
  const [token, setToken] = useState("");
  const [chatId, setChatId] = useState("");
  const [notice, setNotice] = useState("");
  const [noticeError, setNoticeError] = useState(false);
  const update = useMutation({ mutationFn: api.settings.update, onSuccess: (data) => { client.setQueryData(["settings"], data); setToken(""); setChatId(""); setNoticeError(false); setNotice("Telegram settings saved."); }, onError: (error) => { setNoticeError(true); setNotice(error instanceof Error ? error.message : "Could not save Telegram settings."); } });
  const test = useMutation({ mutationFn: api.settings.testTelegram, onSuccess: (data) => { setNoticeError(!data.success); setNotice(data.message); }, onError: (error) => { setNoticeError(true); setNotice(error instanceof Error ? error.message : "Telegram test failed."); } });
  const settings = query.data;
  const save = () => update.mutate({ telegram_enabled: enabled ?? settings?.telegram_enabled, ...(token ? { telegram_bot_token: token } : {}), ...(chatId ? { telegram_chat_id: chatId } : {}) });
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">Service configuration</p><h1>Settings</h1><p className="page-subtitle">Review runtime connectivity and update safe notification preferences.</p></div></div>{notice && <div className={`toast ${noticeError ? "toast-error" : ""}`} role={noticeError ? "alert" : "status"}>{notice}</div>}{query.isLoading ? <div className="panel loading-block">Loading settings…</div> : query.error ? <div className="panel inline-error" role="alert">Could not load settings.</div> : <div className="settings-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Runtime status</p><h2>Service connections</h2></div></div><div className="setting-status-list"><SettingStatus label="API authentication" ok={settings?.api_key_configured} /><SettingStatus label="Browser service" ok={settings?.browser_configured} /><SettingStatus label="Database encryption" ok={settings?.encryption_key_configured} /><SettingStatus label="Telegram" ok={settings?.telegram_configured} detail={settings?.telegram_enabled ? "Enabled" : "Disabled"} /><SettingStatus label="Payment handling" ok detail="not used by panel" /></div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Notifications</p><h2>Telegram delivery</h2></div></div><p className="panel-copy">Only Telegram settings can be changed here. Secrets are sent to the backend and are never returned to the browser.</p><label className="confirm-row"><input type="checkbox" checked={enabled ?? settings?.telegram_enabled ?? false} onChange={(event) => setEnabled(event.target.checked)} /><span><strong>Enable Telegram notifications</strong><small>Receive stock, checkout, and worker failure events.</small></span></label><label>Bot token<input type="password" value={token} onChange={(event) => setToken(event.target.value)} placeholder={settings?.telegram_configured ? "Configured, enter to replace" : "Paste bot token"} autoComplete="off" /></label><label>Chat ID<input value={chatId} onChange={(event) => setChatId(event.target.value)} placeholder={settings?.telegram_configured ? "Configured, enter to replace" : "Numeric chat ID"} /></label><div className="dialog-actions"><button className="button-secondary" onClick={() => test.mutate()} disabled={test.isPending || !settings?.telegram_configured}>Send test</button><button className="button-primary" onClick={save} disabled={update.isPending}>{update.isPending ? "Saving…" : "Save settings"}</button></div></section></div>}</div>;
}

function SettingStatus({ label, ok, detail }: { label: string; ok?: boolean; detail?: string }) { return <div className="setting-status"><span className={`status-dot ${ok ? "status-dot-good" : "status-dot-muted"}`} /><div><strong>{label}</strong><span>{detail ?? (ok ? "Configured" : "Not configured")}</span></div></div>; }
